# Generated by Django 5.0.6 on 2024-06-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sex',
        ),
        migrations.AddField(
            model_name='animal',
            name='death_date',
            field=models.DateField(blank=True, null=[True]),
            preserve_default=[True],
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sold_date',
            field=models.DateField(blank=True, null=[True]),
            preserve_default=[True],
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('camel', 'Camel')], default=type, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='tag_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='SoldAnimal',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
